db:
  image: postgres:latest
  environment:
    POSTGRES_DB: mydb
    POSTGRES_USER: myuser
    POSTGRES_PASSWORD: mypassword
  ports:
    - "5432:5432"
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
    interval: 1m30s
    timeout: 30s
    retries: 5
    start_period: 30s
